name: akbr.net
url: http://chuck.akbr.net/dev/www/_site
assets: http://chuck.akbr.net/dev/www/_site/assets
description: Thoughts by Aaron Rieke
markdown: redcarpet
pygments: true
permalink: posts/:year-:month-:day/:title.html
